#!/bin/bash
[[ "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" =~  .*docker-(.*) ]]

docker run -v `pwd`/jenkins:/root/.jenkins -v /var/run/docker.sock:/run/docker.sock -p 8080:8080 -d ${BASH_REMATCH[1]}
