#!/bin/bash

#sv start socklog-unix || exit 1

source /etc/envvars

mkdir -p /root/.jenkins/plugins
rsync -av /jenkins/plugins/ /root/.jenkins/plugins/

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

exec 2>&1
exec java -Dhudson.model.DirectoryBrowserSupport.CSP= -Djenkins.install.runSetupWizard=false $ARGS -jar /jenkins.war ${PREFIX:"--prefix=$PREFIX"}
