#!/bin/bash

#sv start socklog-unix || exit 1

source /etc/envvars

mkdir -p /root/.jenkins
rm -r /root/.jenkins/plugins
ln -s /jenkins/plugins /root/.jenkins

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

exec 2>&1
exec java -Dpermissive-script-security.enabled=true -Dhudson.model.DirectoryBrowserSupport.CSP= -Djenkins.install.runSetupWizard=false -jar /jenkins.war --prefix=/jenkins
