#!/bin/bash

#sv start socklog-unix || exit 1

source /etc/envvars
env

git config --global user.email "you@example.com"
git config --global user.name "Your Name"

exec 2>&1
exec java -Djenkins.install.runSetupWizard=false -jar /jenkins.war --prefix=/jenkins
